seed: 42
episodes: 100
horizon: 24              # months/periods
env:
  departments: 6
  budget: 10_000_000     # per period
  min_pct_per_unit: 0.03
  max_pct_per_unit: 0.40
  risk_aversion: 0.5
  cvar_alpha: 0.1
  synergy_scale: 0.05
  roi_mu_range: [0.01, 0.04]    # per period return (1%-4%)
  roi_sigma_range: [0.01, 0.06] # per period risk
  strategy_scores: [0.9, 0.8, 0.7, 0.5, 0.6, 0.4]
objectives:
  weights:                  # used by scalarization agent
    npv: 1.0
    risk: 0.6               # penalize variance
    fairness: 0.3           # penalize inequality
    strategy: 0.4           # reward alignment
agent:
  algo: "pg"                # pg | evo
  alpha: 0.05
  gamma: 0.99
eval:
  episodes: 10
  pareto_samples: 64
logging:
  every: 10
  out_dir: "artifacts/run1"
